/*
 * Opalstack API
 *
 *  ## The Opalstack JSON REST API  ### Authorization This API uses an **Authorization** header of the form: `\"Authorization: Token 1111111111111111111111111111111111111111\"`, where **1111111111111111111111111111111111111111** represents an API token created at https://my.opalstack.com/tokens/.  The typical format of an API request looks like the following: ``` GET request:     curl -s -H \"Authorization: Token 1111111111111111111111111111111111111111\" \"https://my.opalstack.com/api/v1/site/list/\" | jq .  POST request:     curl -s -H \"Content-Type: application/json\" -H \"Authorization: Token 1111111111111111111111111111111111111111\" \\             -X POST -d '[{\"id\": \"(site UUID)\", \"redirect\": true, ...}]' \"https://my.opalstack.com/api/v1/site/update/\" | jq . ``` (Further examples will omit **headers** and **jq** for the sake of clarity)  You can also authorize requests on our API Documentation page (https://my.opalstack.com/api/v1/doc/) in order to facilitate development. To do so, click the \"**Authorize**\" button on the right side of the page and enter \"**Token 1111111111111111111111111111111111111111**\" in the **Value** field within. Afterword, you will be able to perform requests directly from the documentation page. Be sure to logout when finished.  ### Embedding The Opalstack API supports _embedding_. This allows you to nest child API objects in a single GET request. For example, consider the following GET request performed with **curl**: ``` Request:     curl \"https://my.opalstack.com/api/v1/osuser/list/\"  Response:     [       {         \"id\": \"01010101-0202-0303-0404-050505050505\",         \"state\": \"READY\",         \"ready\": true,         \"name\": \"the_osuser_name\",         \"server\": \"11111111-1212-1313-1414-151515151515\"       }     ] ```  Suppose then that we would like additional information about the **server**. We _could_ proceed to query the **server** UUID (**11111111-1212-1313-1414-151515151515**) at the `/server/read/{uuid}` endpoint, like this: ``` Request:     curl \"https://my.opalstack.com/api/v1/server/read/11111111-1212-1313-1414-151515151515\"  Response:     {       \"id\": \"11111111-1212-1313-1414-151515151515\",       \"hostname\": \"vpsNNN.opalstack.com\"     } ```  However, we could have instead choosen to specify `?embed=server` as a query parameter to the original GET request. This will cause objects to be _embedded_ in the response directly: ``` Request:     curl \"https://my.opalstack.com/api/v1/osuser/list/?embed=server\"  Response:     [       {         \"id\": \"01010101-0202-0303-0404-050505050505\",         \"state\": \"READY\",         \"ready\": true,         \"name\": \"the_osuser_name\",         \"server\": {           \"id\": \"11111111-1212-1313-1414-151515151515\",           \"hostname\": \"vpsNNN.opalstack.com\"         }       }     ] ``` Here, the **server** field has been be populated with the full object instead of just a UUID.  The **embed** query parameter accepts multiple (comma-separated) fields to embed. For example: ``` curl \"https://my.opalstack.com/api/v1/account/info/?embed=web_servers,imap_servers,smtp_servers\" ```
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MariaCharset string

// List of MariaCharset
const (
	UTF8_MariaCharset     MariaCharset = "utf8"
	ARMSCII8_MariaCharset MariaCharset = "armscii8"
	ASCII_MariaCharset    MariaCharset = "ascii"
	BIG5_MariaCharset     MariaCharset = "big5"
	BINARY_MariaCharset   MariaCharset = "binary"
	CP1250_MariaCharset   MariaCharset = "cp1250"
	CP1251_MariaCharset   MariaCharset = "cp1251"
	CP1256_MariaCharset   MariaCharset = "cp1256"
	CP1257_MariaCharset   MariaCharset = "cp1257"
	CP850_MariaCharset    MariaCharset = "cp850"
	CP852_MariaCharset    MariaCharset = "cp852"
	CP866_MariaCharset    MariaCharset = "cp866"
	CP932_MariaCharset    MariaCharset = "cp932"
	DEC8_MariaCharset     MariaCharset = "dec8"
	EUCJPMS_MariaCharset  MariaCharset = "eucjpms"
	EUCKR_MariaCharset    MariaCharset = "euckr"
	GB2312_MariaCharset   MariaCharset = "gb2312"
	GBK_MariaCharset      MariaCharset = "gbk"
	GEOSTD8_MariaCharset  MariaCharset = "geostd8"
	GREEK_MariaCharset    MariaCharset = "greek"
	HEBREW_MariaCharset   MariaCharset = "hebrew"
	HP8_MariaCharset      MariaCharset = "hp8"
	KEYBCS2_MariaCharset  MariaCharset = "keybcs2"
	KOI8R_MariaCharset    MariaCharset = "koi8r"
	KOI8U_MariaCharset    MariaCharset = "koi8u"
	LATIN1_MariaCharset   MariaCharset = "latin1"
	LATIN2_MariaCharset   MariaCharset = "latin2"
	LATIN5_MariaCharset   MariaCharset = "latin5"
	LATIN7_MariaCharset   MariaCharset = "latin7"
	MACCE_MariaCharset    MariaCharset = "macce"
	MACROMAN_MariaCharset MariaCharset = "macroman"
	SJIS_MariaCharset     MariaCharset = "sjis"
	SWE7_MariaCharset     MariaCharset = "swe7"
	TIS620_MariaCharset   MariaCharset = "tis620"
	UCS2_MariaCharset     MariaCharset = "ucs2"
	UJIS_MariaCharset     MariaCharset = "ujis"
	UTF16_MariaCharset    MariaCharset = "utf16"
	UTF16LE_MariaCharset  MariaCharset = "utf16le"
	UTF32_MariaCharset    MariaCharset = "utf32"
	UTF8MB4_MariaCharset  MariaCharset = "utf8mb4"
)
